import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import KnowMore from '../components/KnowMore'
import OurNumbers from '../components/OurNumbers'
// import Steps from '../components/Steps'

const videoJsOptions = {
  autoplay: false,
  controls: true,
  poster: './assets/video-bg.png',
  responsive: true,
  width: '720',
  sources: [
    {
      src: './assets/mov_bbb.mp4',
      type: 'video/mp4'
    }
  ]
}

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>LGPD Map - Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Presentation />
      <KnowMore {...videoJsOptions} />
      <OurNumbers />
      {/* <Steps /> */}
    </div>
  )
}

export default Home
