import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import KnowMore from '../components/KnowMore'
import OurNumbers from '../components/OurNumbers'
import Steps from '../components/Steps'
import ContactUs from '../components/ContactUs'
import Testimonials from '../components/Testimonials'
import Partners from '../components/Partners'
import Plans from '../components/Plans'
import Footer from '../components/Footer'
import FAQ from '../components/FAQ'

const videoJsOptions = {
  autoplay: false,
  controls: true,
  poster: './assets/video-bg.png',
  responsive: true,
  width: '720',
  sources: [
    {
      src: './assets/LGPD_FINAL.mp4',
      type: 'video/mp4'
    }
  ]
}

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>LGPD Map - Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Presentation />
      <KnowMore {...videoJsOptions} />
      <OurNumbers />
      <Steps />
      <ContactUs />
      <Testimonials />
      <Partners />
      <Plans />
      <FAQ />
      <Footer />
    </div>
  )
}

export default Home
