import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import ContactUs from '../components/ContactUs'
import Testimonials from '../components/Testimonials'
import Partners from '../components/Partners'
import Steps from '../components/Steps/'
import Footer from '../components/Footer'
import FAQ from '../components/FAQ'
import PlansPage from '../components/PlansPage'
import Navbar from '../components/Navbar'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Lgpdmap - Planos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="assets/favicon.ico" />
      </Head>
      <Navbar />
      <Presentation
        title="Confira os planos disponíveis do Lgpdmap"
        paragraph="Possuímos um plano ideal para sua organização ou grupo de empresas. Confira os planos do <strong>Lgpdmap</strong>."
        hasButton="false"
      />
      <PlansPage />
      <ContactUs />
      {/* <Testimonials /> */}
      <Partners />
      <Steps />
      <FAQ />
      <Footer />
    </div>
  )
}

export default Home
