import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import ContactUs from '../components/ContactUs'
import Testimonials from '../components/Testimonials'
import Partners from '../components/Partners'
import Steps from '../components/Steps/'
import Footer from '../components/Footer'
import FAQ from '../components/FAQ'
import PlansPage from '../components/PlansPage'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>LGPD Map - Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Presentation
        title="Conheça os nossos planos"
        paragraph="Possuimos um plano ideal para o tamanho da sua empresa, confira todos planos da LGPDmap"
      />
      <PlansPage />
      <ContactUs />
      <Testimonials />
      <Partners />
      <Steps />
      <FAQ />
      <Footer />
    </div>
  )
}

export default Home
