import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import Footer from '../components/Footer'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>LGPD Map - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="./assets/logo.ico"
          type="image/x-icon"
        />
      </Head>

      <Presentation
        title="Nossa política de privacidade."
        paragraph="Bem-vindo e obrigado pelo seu interesse no LGPDmap (“LGPDmap”, “nós” ou “nos”), nosso site em https://www.lgpdmap.com (o “Site”) e todos os sites relacionados , software para download, aplicativos móveis (incluindo aplicativos para tablets) e outros serviços fornecidos por nós e nos quais um link para esta Política de Privacidade é exibido, e todas as outras comunicações com indivíduos por meio escrito ou oral, como e-mail ou telefone (coletivamente , juntamente com o Site, nosso “Serviço”)."
        hasButton="true"
      />
      <div className="terms">
        <h1>Política de Privacidade</h1>
        <p>
          Esta Política de Privacidade (“Política”) descreve as informações que
          coletamos no ou por meio do Serviço, como usamos e divulgamos tais
          informações e as medidas que tomamos para protegê-las. Ao visitar o
          Site, comprar ou usar o Serviço, você aceita as práticas de
          privacidade descritas nesta Política.
        </p>
        <p>
          This Policy is incorporated into, and is subject to, the LGPDmap Terms
          of Service. Capitalized terms used but not defined in this Policy have
          the meaning given to them in the LGPDmap Terms of Service.
        </p>
      </div>
      <Footer />
    </div>
  )
}

export default Home
