import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import ContactUs from '../components/ContactUs'

import Footer from '../components/Footer'
import FAQ from '../components/FAQ'
import StepsPage from '../components/StepsPage'
import Plans from '../components/Plans'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>LGPD Map - Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Presentation
        title="Conheça os nossos planos"
        paragraph="Possuimos um plano ideal para o tamanho da sua empresa, confira todos planos da LGPDmap"
      />
      <StepsPage />
      <ContactUs />
      <Plans />
      <FAQ />
      <Footer />
    </div>
  )
}

export default Home
