import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import ContactUs from '../components/ContactUs'

import Footer from '../components/Footer'
import FAQ from '../components/FAQ'
import StepsPage from '../components/StepsPage'
import Plans from '../components/Plans'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>LGPD Map - Como Funciona?</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="shortcut icon"
          href="/assets/sekur.png"
          type="image/x-icon"
        />
      </Head>
      <Presentation
        title="Pronto para implantar a LGPD de forma fácil e intuitiva?"
        paragraph={[
          'Saiba como funciona o passo a passo para sua empresa se adequar a',
          <strong> LGPD </strong>,
          'de modo fácil, rápido e simples.'
        ]}
        hasButton="false"
      />
      <StepsPage />
      <ContactUs />
      <Plans />
      <FAQ />
      <Footer />
    </div>
  )
}

export default Home
