import React from 'react'
import Head from 'next/head'
import Presentation from '../components/Presentation'
import Footer from '../components/Footer'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Lgpdmap - Termos de Uso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="assets/favicon.ico" />
      </Head>

      <Presentation
        title="Nossos termos e condições."
        paragraph="Estes Termos de Serviço contêm os termos e condições que regem todo o uso de nossa Plataforma (conforme definido abaixo) e Serviços (conforme definido abaixo) e todo conteúdo, serviços e / ou produtos disponíveis na ou por meio da Plataforma (coletivamente, os “Serviços LGPDmap ”)."
        hasButton="true"
      />
      <div className="terms">
        <h1>Termos e condições</h1>
        <p>
          Os Serviços LGPDmap são oferecidos a você sujeitos à sua aceitação,
          sem modificação (exceto os Termos Especiais (conforme definido abaixo)
          acordado pelas partes de acordo com estes Termos de Serviço), de todos
          os termos e condições aqui contidos e todas as outras regras
          operacionais , políticas (incluindo, sem limitação, nossa Política de
          Privacidade em www.lgpdmap.com/privacy), as Diretrizes (conforme
          definido abaixo) e quaisquer modificações futuras das mesmas, e
          procedimentos que podem ser publicados de tempos em tempos na
          Plataforma ou disponibilizados para você nos ou por meio dos Serviços
          LGPDmap (coletivamente, os “Termos”). Quando aceitos por você
          (conforme definido abaixo), estes Termos formam um contrato legalmente
          vinculativo entre você e o Fornecedor (conforme definido abaixo). Se
          você estiver celebrando estes Termos em nome de uma entidade, como seu
          empregador ou a empresa para a qual trabalha, você declara que tem
          autoridade legal para vincular essa entidade.
        </p>
        <p>
          LEIA ESTES TERMOS COM ATENÇÃO. AO SE REGISTAR, ACESSAR, NAVEGANDO E /
          OU DE OUTRA FORMA USANDO OS SERVIÇOS PIPEDRIVE, VOCÊ RECONHECE QUE
          LEU, COMPREENDEU E CONCORDA EM CUMPRIR ESTES TERMOS. SE VOCÊ NÃO
          CONCORDA COM ESTES TERMOS, NÃO ACESSE, PESQUE OU USE DE OUTRA FORMA A
          PLATAFORMA OU O PIPEDRIVE SERVIÇOS.
        </p>
        <p>
          O Fornecedor pode, a seu exclusivo critério, decidir suspender ou
          encerrar o acesso ou uso dos Serviços LGPDmap para qualquer pessoa que
          violar estes Termos.
        </p>
        <p>
          Se você se registrar para uma avaliação gratuita dos Serviços LGPDmap,
          as disposições aplicáveis.
        </p>
        <p>
          O idioma original destes Termos é o inglês. O fornecedor pode
          disponibilizar traduções por conveniência. Em caso de conflito entre a
          versão original em inglês e qualquer tradução, a versão em inglês
          prevalecerá.
        </p>
      </div>
      <Footer />
    </div>
  )
}

export default Home
